name: hydrate_me
description: Get Hydrated flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_redux: ^0.8.2
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  intl: ^0.17.0
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  flutter_local_notifications: ^9.2.0
  firebase_core_web: ^1.5.4
  firebase_admob: ^0.11.2
  firebase_core: ^1.12.0
  # GetX State Management
  get: ^4.6.1
  get_storage: ^2.0.3
  # Opens app settings
  app_settings: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/buttons/
    - assets/icons/
    - assets/background/