name: App Code Analysis
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

 #concurrency: 
   #group: ${{ github.event.pull_request.number || github.ref }}
   #cancel-in-progress: true

jobs:
  code-analysis-and-testing:
    name: Code Analysis and Testing
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: 'stable' # 'dev', 'alpha', 'master', default to: 'stable'

    - name: Get pub dependencies
      run: flutter pub get

    - name: Flutter analyze
      run: flutter analyze

    # - name: Flutter test TBD Create automated tests
    #   run: flutter test
